GET https://aim-for-more-server.onrender.com /verify"
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2MzMGY4N2MyYjM1MDRiYTBkYzg5MzgiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MTE2NTUyMCwiZXhwIjoxNzQyMDI5NTIwfQ.3MWUgIYSwHUCQ_grbpryGHoCB7E48ASg1NAkeyoxBdg


POST https://aim-for-more-server.onrender.com /login"
Content-Type: application/json

{
"email":"example@gmail.com",
  "password":""
}