GET http://localhost:5000/verify"
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2MzMGY4N2MyYjM1MDRiYTBkYzg5MzgiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MTE2NTUyMCwiZXhwIjoxNzQyMDI5NTIwfQ.3MWUgIYSwHUCQ_grbpryGHoCB7E48ASg1NAkeyoxBdg


POST http://localhost:5000/login"
Content-Type: application/json

{
"email":"example@gmail.com",
  "password":""
}